# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from core.proto import userInteractor_pb2 as userInteractor__pb2


class UserInteractorServiceStub(object):
    """Service definition for user-related operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OnboardUser = channel.unary_unary(
                '/bubbleProto.UserInteractorService/OnboardUser',
                request_serializer=userInteractor__pb2.OnboardUserRequest.SerializeToString,
                response_deserializer=userInteractor__pb2.OnboardUserResponse.FromString,
                )
        self.EncryptToUser = channel.unary_unary(
                '/bubbleProto.UserInteractorService/EncryptToUser',
                request_serializer=userInteractor__pb2.EncryptToUserRequest.SerializeToString,
                response_deserializer=userInteractor__pb2.EncryptToUserResponse.FromString,
                )
        self.IsNullified = channel.unary_unary(
                '/bubbleProto.UserInteractorService/IsNullified',
                request_serializer=userInteractor__pb2.IsNullifiedRequest.SerializeToString,
                response_deserializer=userInteractor__pb2.IsNullifiedResponse.FromString,
                )


class UserInteractorServiceServicer(object):
    """Service definition for user-related operations.
    """

    def OnboardUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncryptToUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsNullified(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserInteractorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OnboardUser': grpc.unary_unary_rpc_method_handler(
                    servicer.OnboardUser,
                    request_deserializer=userInteractor__pb2.OnboardUserRequest.FromString,
                    response_serializer=userInteractor__pb2.OnboardUserResponse.SerializeToString,
            ),
            'EncryptToUser': grpc.unary_unary_rpc_method_handler(
                    servicer.EncryptToUser,
                    request_deserializer=userInteractor__pb2.EncryptToUserRequest.FromString,
                    response_serializer=userInteractor__pb2.EncryptToUserResponse.SerializeToString,
            ),
            'IsNullified': grpc.unary_unary_rpc_method_handler(
                    servicer.IsNullified,
                    request_deserializer=userInteractor__pb2.IsNullifiedRequest.FromString,
                    response_serializer=userInteractor__pb2.IsNullifiedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bubbleProto.UserInteractorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserInteractorService(object):
    """Service definition for user-related operations.
    """

    @staticmethod
    def OnboardUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bubbleProto.UserInteractorService/OnboardUser',
            userInteractor__pb2.OnboardUserRequest.SerializeToString,
            userInteractor__pb2.OnboardUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EncryptToUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bubbleProto.UserInteractorService/EncryptToUser',
            userInteractor__pb2.EncryptToUserRequest.SerializeToString,
            userInteractor__pb2.EncryptToUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsNullified(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bubbleProto.UserInteractorService/IsNullified',
            userInteractor__pb2.IsNullifiedRequest.SerializeToString,
            userInteractor__pb2.IsNullifiedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
