# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userInteractor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14userInteractor.proto\x12\x0b\x62ubbleProto\"U\n\x12OnboardUserRequest\x12\x16\n\x0ersa_public_key\x18\x01 \x01(\x0c\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0c\x12\x16\n\x0euser_signature\x18\x03 \x01(\x0c\"[\n\x13OnboardUserResponse\x12\x17\n\x0frsa_ciphertexts\x18\x01 \x01(\x0c\x12\x16\n\x0empc_signatures\x18\x02 \x03(\x0c\x12\x13\n\x0bresult_code\x18\x03 \x01(\x05\"Q\n\x14\x45ncryptToUserRequest\x12\x0f\n\x07handles\x18\x01 \x03(\x0c\x12\x10\n\x08\x63hain_id\x18\x02 \x01(\x03\x12\x16\n\x0euser_signature\x18\x03 \x01(\x0c\"U\n\x15\x45ncryptToUserResponse\x12\x0f\n\x07outputs\x18\x01 \x03(\x0c\x12\x16\n\x0empc_signatures\x18\x02 \x03(\x0c\x12\x13\n\x0bresult_code\x18\x03 \x01(\x05\"&\n\x12IsNullifiedRequest\x12\x10\n\x08y_values\x18\x01 \x03(\x0c\"T\n\x13IsNullifiedResponse\x12\x11\n\tresponses\x18\x01 \x03(\x08\x12\x15\n\rmpc_signature\x18\x02 \x01(\x0c\x12\x13\n\x0bresult_code\x18\x03 \x01(\x05\x32\x93\x02\n\x15UserInteractorService\x12P\n\x0bOnboardUser\x12\x1f.bubbleProto.OnboardUserRequest\x1a .bubbleProto.OnboardUserResponse\x12V\n\rEncryptToUser\x12!.bubbleProto.EncryptToUserRequest\x1a\".bubbleProto.EncryptToUserResponse\x12P\n\x0bIsNullified\x12\x1f.bubbleProto.IsNullifiedRequest\x1a .bubbleProto.IsNullifiedResponseB\x10Z\x0e./;bubbleProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'userInteractor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016./;bubbleProto'
  _globals['_ONBOARDUSERREQUEST']._serialized_start=37
  _globals['_ONBOARDUSERREQUEST']._serialized_end=122
  _globals['_ONBOARDUSERRESPONSE']._serialized_start=124
  _globals['_ONBOARDUSERRESPONSE']._serialized_end=215
  _globals['_ENCRYPTTOUSERREQUEST']._serialized_start=217
  _globals['_ENCRYPTTOUSERREQUEST']._serialized_end=298
  _globals['_ENCRYPTTOUSERRESPONSE']._serialized_start=300
  _globals['_ENCRYPTTOUSERRESPONSE']._serialized_end=385
  _globals['_ISNULLIFIEDREQUEST']._serialized_start=387
  _globals['_ISNULLIFIEDREQUEST']._serialized_end=425
  _globals['_ISNULLIFIEDRESPONSE']._serialized_start=427
  _globals['_ISNULLIFIEDRESPONSE']._serialized_end=511
  _globals['_USERINTERACTORSERVICE']._serialized_start=514
  _globals['_USERINTERACTORSERVICE']._serialized_end=789
# @@protoc_insertion_point(module_scope)
