name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      REMOTE_RPC_URL: ${{ vars.REMOTE_ETHEREUM_RPC_URL}}
      REMOTE_CHAIN_ID: ${{ vars.REMOTE_ETHEREUM_CHAIN_ID}}
      REMOTE_FAUCET_ADDRESS: ${{ secrets.REMOTE_FAUCET_ADDRESS}}
      USER_INTERACTOR_URL: ${{ vars.USER_INTERACTOR_URL}}:50060
      CHAIN_NAME: ${{ vars.CHAIN_NAME}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install requirements
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          npm install

      # - name: Onboard user - js
      #   run: |
      #     chmod +x lib/onchain/scripts/js/gen-account.mjs
      #     node lib/onchain/scripts/js/gen-account.mjs .env_user
      #     source .env_user
      #     python -m lib.onchain.scripts.python.transfer_native_coins "$REMOTE_FAUCET_ADDRESS" Remote
      #     chmod +x lib/offchain/onboardUser/js/onboard-user.mjs 
      #     node lib/offchain/onboardUser/js/onboard-user.mjs Remote
      #   timeout-minutes: 5
      #   env:
      #     DISABLE_GAS_ESTIMATION: "true"

      # - name: Run js ERC20
      #   run: |
      #     source .env_user
      #     node examples/scripts/js/run-private-erc20.mjs Remote
      #   timeout-minutes: 5

      # - name: Run js ERC20 with EIP 191 signatures
      #   run: |
      #     source .env_user
      #     node examples/scripts/js/run-private-erc20.mjs --use_eip191_signature=true Remote
      #   timeout-minutes: 5

      - name: Onboard user - python
        run: |
          # rm .env_user
          chmod +x lib/onchain/scripts/python/gen_account.py
          python -m lib.onchain.scripts.python.gen_account .env_user
          source .env_user
          python -m lib.onchain.scripts.python.transfer_native_coins "$REMOTE_FAUCET_ADDRESS" Remote
          chmod +x lib/offchain/onboardUser/python/onboard_user.py
          python -m lib.offchain.onboardUser.python.onboard_user Remote
        timeout-minutes: 5

      - name: Run tests
        run: |
          source .env_user
          python -m tests.scripts.python.run_mpc_tests_contract Remote --user_interactor_url "$USER_INTERACTOR_URL"
        timeout-minutes: 15

      - name: Run python ERC20 tests
        run: |
          source .env_user
          python -m examples.scripts.python.run_private_erc20 Remote
        timeout-minutes: 5

      - name: Run python ERC20 tests with EIP 191 signatures
        run: |
          source .env_user
          python -m examples.scripts.python.run_private_erc20 Remote --use_eip191_signature=True
        timeout-minutes: 5

      - name: Check Exit Codes
        run: |
          if [ ${{ job.status }} == "success" ]; then
            echo "All processes exited with exit code 0."
          else
            echo "One or more processes did not exit with exit code 0."
          fi
  notify:
    runs-on: ubuntu-latest
    needs: build
    if: failure()

    steps:
      - name: Send Slack Notification on failure
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: |
            The workflow ${{ github.workflow }} has failed.
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
